### ISSUE TITLE
Vim/nano/etc do not scale correctly, and scrolling doesn't work well.

### ISSUE THREAD

**Issue by kitft** [i-am-shodan/ReTerm#13]
Both vim and nano open at a size smaller than expected for the window size. In vim, this is &columns = 80, &lines=24. I can't resize vim (using e.g. ":set lines=30") to any size larger than 24. The command succeeds, but the new frame is not drawn. See photos:

![IMG_1552](https://github.com/i-am-shodan/ReTerm/assets/58341426/4f4da0b5-e403-4862-ae00-f77bae2fca75)
![IMG_1553](https://github.com/i-am-shodan/ReTerm/assets/58341426/61fe4378-8360-4b32-8de2-826287aefe7c)

Also, scrolling doesn't work well in vim. If I move a large number of lines, everything is redrawn (e.g. skipping to the top or bottom with _G_ or _gg_ works perfectly well). However, moving the cursor downwards one line at a time from the bottom of the screen only updates the bottom line (so that it skips from e.g. 21 to 33). Is this somehow related to the lack of scrolling in the shell? You mentioned you got rid of that to stop too many redraws. Here's a picture:

![IMG_1554](https://github.com/i-am-shodan/ReTerm/assets/58341426/a8efa909-de8d-4644-b722-3fe5a77e353b)

Thanks for the project! I wish I could do anything more useful than filing issues.

_PS: I'm sure you know about this already, so I won't bother submitting it as an independent issue. If your shell input is longer than a line, it wraps back on its own line:_

![IMG_1556](https://github.com/i-am-shodan/ReTerm/assets/58341426/fbe55c5f-2c79-4491-bdf3-8a82e19c21af)

**Comment by i-am-shodan** [comment]
I've done to major updates to this which can be found in the latest release. https://github.com/i-am-shodan/ReTerm/releases/tag/release_20230731_1832

Feel free to create new issues
