### ISSUE TITLE
Compatibility with remarkable 2 os 3.5+.

### ISSUE THREAD

**Issue by IshmaelBelghazi** [i-am-shodan/ReTerm#15]
ReTerm is precisely what I was looking for. Is it compatible with remarkable 2 os 3.5+? 

Any idea on how to access the terminal from the remarkable gui?

I'll be more than willing to help with the documentation on these questions.

**Comment by i-am-shodan** [comment]
It should work on any remarkable fw version but you'll need 3.2 or better to support the folio.

Install via Toltec and it will automatically appear in your launcher. I personally use Remux but oxide is the most popular I think.
