### ISSUE TITLE
Feat: White background

### ISSUE THREAD

**Issue by kiwiz** [i-am-shodan/ReTerm#2]
Version: `20230616_1633`

It'd be nice if the color scheme was inverted so that the background is white and text is black.

**Comment by i-am-shodan** [comment]
The background is white and the text is black...
Just look at the videos on the main page

**Comment by kiwiz** [comment]
Hmm, I'm seeing this though:
<img width="1029" alt="Screenshot 2023-06-26 at 10 29 55 AM" src="https://github.com/i-am-shodan/ReTerm/assets/3122114/b8116807-efce-4bc0-ba43-01fa6ec8342b">

**Comment by i-am-shodan** [comment]
Well this is very exciting. I don't have that on mine! Are you using the latest release? Are you using the single binary release? Write back and I'll test.

**Comment by kiwiz** [comment]
Yup, I'm using no-dotnet release here: https://github.com/i-am-shodan/ReTerm/releases/tag/release_20230616_1633

**Comment by i-am-shodan** [comment]
Can you try the previous revision and see if it's the same. I made some changes this release

**Comment by kiwiz** [comment]
Yup, I can confirm that [20230606_1233](https://github.com/i-am-shodan/ReTerm/releases/tag/release_20230606_1233) works as expected.

**Comment by i-am-shodan** [comment]
Hmmm, I've just downloaded the latest release and tested it. I get black text on a white background.

Can I ask you to load up ReTerm and then type 'export' and send me a screenshot. And just to confirm you haven't edited your .bashrc file to change the colours?

**Comment by i-am-shodan** [comment]
The emulator behaves likes your device so I'm currently thinking there is something odd about my setup.

**Comment by kiwiz** [comment]
Nope, pretty stock config.
Here's the output:
```
RM2FB_ACTIVE=1
PWD=/home/root
KO_DONT_GRAB_INPUT=1
LD_PRELOAD=/opt/lib/librm2fb_client.so.1
HOME=/home/root
LANG=C
KO_DONT_SET_DEPTH=1
INVOCATION_ID=0c57806a6c0345c18a09aed16d708c4a
RM2FB_SHIM=0.1
TERM=vt100
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
SHLVL=2
RM2FB_NESTED=1
JOURNAL_STREAM=8:15281
PATH=/opt/bin:/opt/sbin:/home/root/.local/bin:/usr/local/sbin:/usr/l
ocal/bin:/usr/sbin:/usr/bin:/sbin:/bin
DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY=false
_=/usr/bin/env
```

**Comment by i-am-shodan** [comment]
That output was captured by ReTerm? The term variable is set as vt100

**Comment by kiwiz** [comment]
Yup, from this version: [20230606_1233](https://github.com/i-am-shodan/ReTerm/releases/tag/release_20230606_1233)

**Comment by i-am-shodan** [comment]
OK i've found the bug. What version of the rm2 software are you using.

Seems that on my version the .bashrc sets up the prompt in a way that isn't standard.

**Comment by i-am-shodan** [comment]
Fixed in latest release

**Comment by kiwiz** [comment]
Thanks! For posterity: 3.2.3.1595
