### ISSUE TITLE
Special characters replaced by black boxes

### ISSUE THREAD

**Issue by ingatellent** [i-am-shodan/ReTerm#7]
ReTerm shows a black box (▮) instead of certain characters (most significantly ~, which is shown in the default prompt).

I have installed toltec and rm2fb on my rm2 running version 3.2.3.1595
I have copied the folder from the latest release ([20230707_2058](https://github.com/i-am-shodan/ReTerm/releases/tag/release_20230707_2058)) which doesn't require dotnet.

When I ssh into my remarkable and run
systemctl stop xochitl
./ReTerm.sh
ReTerm correctly boots up, but instead of showing "reMarkable: ~/" it shows "reMarkable: ▮/".

I have created a file (qwerty.txt) with some characters, and I attach pictures of the output of cat qwerty.txt in ReTerm as well as in yaft (which handles the characters fine).

It looks like the special Danish characters æ, ø, å, Æ, Ø and Å (last line in the file) have no chance of being rendered since they are not included in the Ubuntu font, but ~, { and } should be displayed correctly.

It would be very nice, if in addition to fixing the problems with ~, { and }, that the default font was replaced by a font with a much broader set of characters (Usecase: ssh to your computer/server edit files in all sorts of encodings).

![ReTerm](https://github.com/i-am-shodan/ReTerm/assets/750082/be6964c7-e1b6-4507-a472-fb2fd590c69c)
[yaft](https://github.com/i-am-shodan/ReTerm/assets/750082/8237ed45-5e6a-4333-8df5-c7e2885f9e5e)
[qwerty.txt](https://github.com/i-am-shodan/ReTerm/files/12039789/qwerty.txt)

**Comment by i-am-shodan** [comment]
So the black box with the tilda (and probably others) is related to the font colour override settings. If you go into ~/.ReTerm/settings.json and set ForceBackgroundHexColor and ForceForegroundHexColor to "" it will probably go away - but you may experience other issues. Try and see if it works for you.

As for the font if you have a recommendation for another font I'll try it out. Otherwise the next version I'm testing has the ability to override the font and size.

**Comment by ingatellent** [comment]
I can indeed confirm, that removing the black and white hex codes makes the chraracters visible again.

Also: All chraracters displays with no issue - also the Danish ones, so no need to change font on these grounds.

However, the issue now is: It is impossible to set the color scheme to black on white, as the default apparently is white on black.

**Comment by i-am-shodan** [comment]
Reopening this because its still an issue

**Comment by i-am-shodan** [comment]
> I can indeed confirm, that removing the black and white hex codes makes the chraracters visible again.
> 
> Also: All chraracters displays with no issue - also the Danish ones, so no need to change font on these grounds.
> 
> However, the issue now is: It is impossible to set the color scheme to black on white, as the default apparently is white on black.

Yep and if you open vim/nano everything gets a bit confused. Someone needs to do some research here about the most correct way to set the terminal colours.

**Comment by robeving** [comment]
This has been fixed in release_20230714_0928. I recommend deleting ~/.ReTerm/settings.json and trying again with the defaults as a lot of bugs have been fixed

**Comment by i-am-shodan** [comment]
Stupid multiple accounts me
